### ISSUE TITLE
Failed to downvote user

### ISSUE THREAD

**Issue by shadowht** [mike-duran-mitchell/petty-reddit-downvoter#1]
I am aways getting, is it broke?

>  Failed to downvote user: randomusername. Check your inputs and try again.

**Comment by mike-duran-mitchell** [comment]
Hi shadowht, I just updated the code. Please try again. If you are using the name '[randomusername](https://www.reddit.com/user/randomusername)' as a target to downvote, you will not be able to downvote their posts because all reddit posts are archived after 1 month. 'randomusername' has not posted in 2 years.

**Comment by shadowht** [comment]
Working now, also I had to change the credentials syntax to this:

```
{
  "userAgent": "xx",
  "client_id": "xx",
  "client_secret": "xxx"
  "password": "xx",
  "username": "xxx"
}
```

It was giving some strange syntax errors with the default one:

```
SyntaxError: C:\Users\xxx\client_credentials.json: Unexpected token u in JSON at position 4
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (module.js:671:27)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\xxx\index.js:23:21)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

Thanks!

**Comment by mike-duran-mitchell** [comment]
That is strange. Those credentials are straight out of [snoowrap](https://github.com/not-an-aardvark/snoowrap) and are still working for me. That api also has not changed since this repo was created.
